Coded by codegea
Hacktoberfest-GYE/hacktoberfestgye-landing pull request #29
Opened 2024-10-14 22:35 UTC by bjgavilanes

I put this information because recently, we had to remove coded_by tag in our webpage.

We would like to thank Codegea team:

@pintoderian 
@cpdavila 

for their contribution.

Visit [Codegea webpage](https://codegea.com/) to discover how their cutting-edge web development can help you:

- Increase your online visibility
- Improve user experience
- Boost sales and conversion
- Outshine the competition

Their web development experts create fast, secure, and efficient websites designed to drive your online success.

2024-10-15 13:29 UTC, jhon-p16 approved these changes

2024-10-15 13:49 UTC, jhon-p16 requested changes
I think we should add "developed by the community" and recognize those who contributed to this development

2024-10-15 14:38 UTC, bjgavilanes commented
Totally. Do you have any reference on how to implement it?

I was thinking about putting a "Coded by: Hactoberfest team and community";
and then, link that tag to a webpage with all our contributors.

Have any pointers?

El mar., 15 de octubre de 2024 10:49 a. m., Jhon Paulo JP <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> I think we should add "developed by the community" and recognize those who
> contributed to this development
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hacktoberfest-GYE/hacktoberfestgye-landing/pull/29#pullrequestreview-2369417433>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3YSTNCM42HCTT5R4T4KZS3Z3UMOTAVCNFSM6AAAAABP53V5J2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRZGQYTONBTGM>
> .
> You are receiving this because you authored the thread.Message ID:
> <Hacktoberfest-GYE/hacktoberfestgye-landing/pull/29/review/2369417433@
> github.com>
>

2024-10-17 15:15 UTC, davcortez commented
> I was thinking about putting a "Coded by: Hactoberfest team and community"; and then, link that tag to a webpage with all our contributors.

That sounds good to me. So, let's whip that up.

2024-10-18 15:30 UTC, closed without merging